// Version is read from VERSION file at build time
// This file is auto-generated by Makefile version target
// Do not edit manually

export const APP_VERSION = "0.0.14";

// Function to get version from backend health endpoint
export const getVersionFromBackend = async (apiBaseUrl: string): Promise<string | null> => {
  try {
    const response = await fetch(`${apiBaseUrl}/api/v1/health`);
    if (response.ok) {
      const data = await response.json();
      return data.version || null;
    }
  } catch (error) {
    console.error("Failed to fetch version from backend:", error);
  }
  return null;
};
