"""rename_subitems_to_purchases

Revision ID: c1dc44446e42
Revises: ffb60a1d2de7
Create Date: 2025-11-22 13:07:35.318147

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1dc44446e42"
down_revision: str | Sequence[str] | None = "ffb60a1d2de7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("purchases", sa.JSON(), nullable=True))
    op.drop_column("expenses", "subitems")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("subitems", sqlite.JSON(), nullable=True))
    op.drop_column("expenses", "purchases")
    # ### end Alembic commands ###
