"""add_incomes_table

Revision ID: cec4e4d0d327
Revises: c2adb22eb41d
Create Date: 2025-11-22 22:52:34.865029

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cec4e4d0d327"
down_revision: str | Sequence[str] | None = "c2adb22eb41d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incomes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("income_type", sa.String(), nullable=False),
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("month_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["month_id"], ["months.id"], name=op.f("fk_incomes_month_id")),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_incomes_id"), "incomes", ["id"], unique=False)
    op.create_index(op.f("ix_incomes_income_type"), "incomes", ["income_type"], unique=False)
    op.create_index(op.f("ix_incomes_month_id"), "incomes", ["month_id"], unique=False)
    op.create_index(op.f("ix_incomes_period"), "incomes", ["period"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_incomes_period"), table_name="incomes")
    op.drop_index(op.f("ix_incomes_month_id"), table_name="incomes")
    op.drop_index(op.f("ix_incomes_income_type"), table_name="incomes")
    op.drop_index(op.f("ix_incomes_id"), table_name="incomes")
    op.drop_table("incomes")
    # ### end Alembic commands ###
