"""add_subitems_json_field_to_expenses

Revision ID: ffb60a1d2de7
Revises: ccb0d14d1d51
Create Date: 2025-11-22 12:55:09.704599

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffb60a1d2de7"
down_revision: str | Sequence[str] | None = "ccb0d14d1d51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("subitems", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expenses", "subitems")
    # ### end Alembic commands ###
